### ISSUE TITLE
Feature: SAP files

### ISSUE THREAD

**Issue by pfusik** [lybrown/dis#2]
Please support the [SAP file format](http://asap.sourceforge.net/sap-format.html).

Suggested output format:

        opt	h-
        dta	c'SAP',13,10
        dta	c'AUTHOR "Tomasz Liebich"',13,10
        dta	c'NAME "Perestroyka - stereo"',13,10
        dta	c'DATE "1989"',13,10
        dta	c'SONGS 6',13,10
        dta	c'STEREO',13,10
        dta	c'TYPE D',13,10
        dta	c'INIT 2003',13,10
        dta	c'PLAYER 2000',13,10
        dta	c'TIME 00:09.70 LOOP',13,10
        dta	c'TIME 01:13.70 LOOP',13,10
        dta	c'TIME 00:48.67 LOOP',13,10
        dta	c'TIME 00:53.32 LOOP',13,10
        dta	c'TIME 00:55.09 LOOP',13,10
        dta	c'TIME 01:12.42 LOOP',13,10
        opt	h+
    ; a XEX follows
        org	f:$2000
        ...

**Comment by lybrown** [comment]
Added to v0.4.
